version: '3.8'

services:
  #web-app container
  web-app:
    build: ./
    command: ./wait-for-postgres.sh db ./web-app
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - db
    environment:
      - DB_PASSWORD=qwerty
    networks:
      - "web-app.network"
  # db container
  db:
    restart: always
    image: postgres:latest
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=qwerty
    ports:
      - "5436:5432"
    networks:
      - "web-app.network"
  #cetbot container for SSL Certificate
  certbot:
    image: certbot/certbot
    restart: unless-stopped
    container_name: certbot
    volumes:
     - ./data/certbot/conf:/etc/letsencrypt
     - ./data/certbot/www:/var/www/certbot
    depends_on:
      - nginx
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
  #nginx container
  nginx:
    image: nginx:latest
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    depends_on:
      - web-app
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    networks:
      - "web-app.network"
networks:
  web-app.network:
